# Generated by Django 5.0.4 on 2024-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
