# Generated by Django 5.0.4 on 2024-05-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_tickettype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
