# Generated by Django 5.0.4 on 2024-04-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('event_management', '0003_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
    ]
