# Generated by Django 5.0.4 on 2024-04-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.ManyToManyField(related_name='events', through='event_management.RoleManagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('organiser', 'Organiser'), ('host', 'Host'), ('volunteer', 'Volunteer'), ('crew_member', 'Crew Member'), ('attendees', 'Attendees')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolemanagement',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_management.role'),
        ),
    ]
