# Generated by Django 5.0.4 on 2024-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_event_role_alter_role_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('organiser', 'Organiser'), ('host', 'Host'), ('volunteer', 'Volunteer'), ('attending', 'Attending'), ('not_attending', 'Not Attending'), ('attendees', 'Attendees')], max_length=20),
        ),
    ]
