# Generated by Django 5.0.4 on 2024-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_donor_auction_donormanagement_customuser_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bidItem',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_raffle',
            field=models.BooleanField(default=False),
        ),
    ]
