# Generated by Django 5.0.4 on 2024-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
